title: bnvulpe
url:  http://127.0.0.1:4000
baseurl: 

author: bnvulpe

include: ['_pages']

collections_dir: series

collections:
  artwork:
    output: true
  elit:
    output: true
  locus:
    output: true
    
markdown: kramdown
kramdown:
  input: GFM